site_name: {{ cookiecutter.project_name }}
repo_url: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}
theme: readthedocs
markdown_extensions:
    - toc:
        permalink: True
